module.exports = {
  content: ['./deploy/**/*.{html,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#2b4963',
        'on-error': '#ffffff',
        'on-surface-variant': '#43474d',
        'on-background': '#1c1c19',
        'secondary-fixed': '#cce5ff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c3c7ce',
        'tertiary-fixed-dim': '#ffb2be',
        tertiary: '#3c0315',
        'inverse-on-surface': '#f3f0eb',
        'primary-fixed-dim': '#abcae9',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'surface-container': '#f0ede8',
        'inverse-surface': '#31302d',
        'on-surface': '#1c1c19',
        'on-secondary-container': '#42627e',
        'on-tertiary-container': '#d67d8e',
        'surface-container-low': '#f6f3ee',
        'on-secondary': '#ffffff',
        'secondary-container': '#bcdefe',
        'on-error-container': '#93000a',
        'tertiary-container': '#581829',
        'surface-container-high': '#ebe8e3',
        'secondary-fixed-dim': '#a9caea',
        outline: '#73777e',
        'error-container': '#ffdad6',
        'surface-tint': '#44617c',
        surface: '#fcf9f4',
        'on-primary-fixed': '#001d32',
        'on-tertiary-fixed': '#3d0315',
        'on-primary-container': '#7d9ab8',
        secondary: '#41627d',
        'on-tertiary-fixed-variant': '#762f3f',
        'on-secondary-fixed': '#001e31',
        background: '#fcf9f4',
        primary: '#001d31',
        'on-primary': '#ffffff',
        'primary-container': '#11324b',
        'surface-container-highest': '#e5e2dd',
        'surface-bright': '#fcf9f4',
        'on-secondary-fixed-variant': '#284a64',
        'tertiary-fixed': '#ffd9de',
        'inverse-primary': '#abcae9',
        'primary-fixed': '#cde5ff',
        'surface-variant': '#e5e2dd',
        'surface-dim': '#dcdad5',
        'burgundy-deep': '#800020',
        'burgundy-rich': '#722F37',
        'burgundy-light': '#9B2335',
        'burgundy-muted': '#A0526B',
        'burgundy-bg': '#2A0A14',
      },
      fontFamily: {
        sans: ['Montserrat', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
